### ISSUE TITLE
Symfony 5.1 incompatibility

### ISSUE THREAD

**Issue by amustill** [yceruto/rich-form-bundle#5]
When upgrading an application from Symfony 5.0.* to 5.1, all calls to `Entity2Type` were broken by a `TypeError`.

`Return value of Yceruto\Bundle\RichFormBundle\Form\ChoiceList\Loader\Entity2LoaderDecorator::loadValuesForChoices() must be of the type array, null returned`

It's the end of the day here so I haven't had a chance to investigate further, but I just wanted to note the issue quickly.

**Comment by yceruto** [comment]
Hi @amustill, I will take a look, thanks for reporting it

**Comment by yceruto** [comment]
The error is related to Symfony code, I've proposed the bugfix there https://github.com/symfony/symfony/pull/37499

**Comment by amustill** [comment]
@yceruto Thanks for the update. Hopefully this will get merged pretty quickly.

**Comment by yceruto** [comment]
I just released 2.0.0 for 5.1+ compatibility
